### PR TITLE
WIP – Complete rewrite

### PR DESCRIPTION
**Pull request by codingjoe**
Hi @relekang 
how are you doing. This took me a while. As discussed online, in order to address my concerns I needed to make some conceptional changes. Eventually I ended up deleting everything and starting from scratch.

As a first step, I would recommend to simply check out the documentation I wrote:
```shell
python setup.py build_sphinx
```

I did follow the example of password reset link. So an identifier and a hmac signature. The identifier is a non natural PK, which should solve the GDPR concern.

You will further see, that I did not longer need to persist anything, which is why the model is gone.

I added Django admin support as an optional feature. This should also allow you to quickly test my changes. On the other hand, I did remove the DRF and twilio integration. Instead I created an easy entry point to extend the library. I also added documentation and an example how to add twilio support. This make the library more lightweight and maintainable, while giving everyone the chance to build what they need.

The I removed the DRF part too. I would always recommend to go with JWT on a JSON API and there is already a very good library for it, seealso https://getblimp.github.io/django-rest-framework-jwt/

I still need to write more tests. But besides that what do you think?
I know it's a lot at once and a I do believe it's worth the effort.

Best
-Joe

### CODE REVIEW

**Comment by relekang** [comment]
This PR is too big, does too many unrelated changes. A lot of this is not needed to fix the security concerns you have raised. Furthermore, putting this in once commit named "Major refactoring" is going to help review this.

Dropping the rest endpoints is not a good idea, even when using the jwt package one needs to authenticate to get the jwt token.

It seems you want this package to be something else than it is, maybe it is better to create another one?

**Comment by codingjoe** [comment]
> This PR is too big, does too many unrelated changes. A lot of this is not needed to fix the security concerns you have raised. Furthermore, putting this in once commit named "Major refactoring" is going to help review this.
> 
> Dropping the rest endpoints is not a good idea, even when using the jwt package one needs to authenticate to get the jwt token.
> 
> It seems you want this package to be something else than it is, maybe it is better to create another one?

You make a fair point. I did not intend this to be reviewed on a code base yet, rather from a conceptional standpoint. The concept changes where necessary or sensical because of the changed security design. I am happy to simply create another package. But to be honest, I would rather have one that is well maintained and secure. Also if I don't fix the security concerns, who will? This leaves all your users vulnerable.

I know that I did drop the REST support for now, but mainly because I didn't have the time to do more. I don't really understand the use case yet.

So how are we going to continue?

**Comment by relekang** [comment]
> You make a fair point. I did not intend this to be reviewed on a code base yet, rather from a conceptional standpoint. The concept changes where necessary or sensical because of the changed security design. I am happy to simply create another package. But to be honest, I would rather have one that is well maintained and secure. Also if I don't fix the security concerns, who will? This leaves all your users vulnerable.

I kind of have the same concern, if these problems are fixed in a huge rewrite it will make it harder for users to patch. I think we can mitigate these issues without these large breaking changes and then rather evaluate if it makes sense to do that later. I'll try to get up a fix tonight.

**Comment by codingjoe** [comment]
@relekang sounds good. Let me know if there is anything I can review for you.

**Pull request closed without merging**
