### PR TITLE
Add request as first positional argument to authenticate

### PR DESCRIPTION
**Pull request by jbeyers**
Fixes https://github.com/relekang/django-nopassword/issues/77

### CODE REVIEW

**Comment by relekang** [comment]
Thanks :v:
I have a few instances that has not been upgraded yet that I can test with, since you mentioned in #77 that you were unsure about how it would affect other versions.

It would be awesome if we were able to create a test that will break without this change.

**Comment by jbeyers** [comment]
I added django 1.11 to tox.ini, reverted my change, and it fails:

ERROR:   flake8: commands failed
  isort: commands succeeded
  py2-django1_8: commands succeeded
  py2-django1_9: commands succeeded
  py2-django1_10: commands succeeded
ERROR:   py2-django1_11: commands failed
  py3-django1_8: commands succeeded
  py3-django1_9: commands succeeded
  py3-django1_10: commands succeeded
ERROR:   py3-django1_11: commands failed
  coverage: commands succeeded

I then reinstated the change, and it passes:

ERROR:   flake8: commands failed
  isort: commands succeeded
  py2-django1_8: commands succeeded
  py2-django1_9: commands succeeded
  py2-django1_10: commands succeeded
  py2-django1_11: commands succeeded
  py3-django1_8: commands succeeded
  py3-django1_9: commands succeeded
  py3-django1_10: commands succeeded
  py3-django1_11: commands succeeded
  coverage: commands succeeded

**Comment by relekang** [comment]
Thank you, this is published as 3.0.2 🙂

**Comment by jbeyers** [comment]
Nice! Thanks!

**Pull request merged**
